# Generated by Django 5.1 on 2025-04-02 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faithlink', '0002_parishioner_date_approved_parishioner_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='parishioner',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parishioner',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='parishioner',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='parishioner',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('S', 'Single'), ('M', 'Married'), ('W', 'Widowed'), ('D', 'Divorced'), ('O', 'Other')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='parishioner',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
