# Generated by Django 5.1 on 2025-04-11 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faithlink', '0004_event_prayerrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date']},
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='event',
            name='actions',
        ),
    ]
