# Generated by Django 5.1 on 2025-04-12 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faithlink', '0008_alter_donation_donor'),
    ]

    operations = [
        migrations.AddField(
            model_name='parishioner',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='parishioner',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
