# Generated by Django 5.1 on 2025-04-12 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faithlink', '0009_parishioner_first_name_parishioner_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faithlink.parishioner'),
        ),
    ]
