# Generated by Django 5.1 on 2025-04-12 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faithlink', '0010_alter_donation_donor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='amount',
        ),
        migrations.AddField(
            model_name='donation',
            name='value',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Estimated value of the donation (monetary or item)', max_digits=10),
            preserve_default=False,
        ),
    ]
