# Generated by Django 5.1 on 2025-04-14 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faithlink', '0011_remove_donation_amount_donation_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundraisingCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('goal_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('raised_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='prayerrequest',
            old_name='request_description',
            new_name='prayer_request',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='value',
        ),
        migrations.RemoveField(
            model_name='prayerrequest',
            name='date_approved',
        ),
        migrations.RemoveField(
            model_name='prayerrequest',
            name='date_closed',
        ),
        migrations.RemoveField(
            model_name='prayerrequest',
            name='request_date',
        ),
        migrations.RemoveField(
            model_name='prayerrequest',
            name='request_title',
        ),
        migrations.RemoveField(
            model_name='prayerrequest',
            name='status',
        ),
        migrations.RemoveField(
            model_name='prayerrequest',
            name='user',
        ),
        migrations.AddField(
            model_name='donation',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donation',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prayerrequest',
            name='parishioner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='faithlink.parishioner'),
            preserve_default=False,
        ),
    ]
