# Generated by Django 5.1 on 2025-04-14 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faithlink', '0012_fundraisingcampaign_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrayerRequest',
        ),
    ]
