# Generated by Django 5.1 on 2025-04-14 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faithlink', '0013_delete_prayerrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrayerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prayer_request', models.TextField()),
                ('parishioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faithlink.parishioner')),
            ],
        ),
    ]
