# Generated by Django 5.1 on 2025-04-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faithlink', '0014_prayerrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='parishioner',
            name='face_image',
            field=models.ImageField(blank=True, null=True, upload_to='faces/'),
        ),
    ]
