# Generated by Django 5.1 on 2025-05-01 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faithlink', '0015_parishioner_face_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', models.JSONField()),
                ('image', models.ImageField(upload_to='face_images/')),
                ('parishioner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='faithlink.parishioner')),
            ],
        ),
    ]
