# Generated by Django 5.1 on 2025-05-29 00:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faithlink', '0016_faceembedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='parishioner',
            name='parishioner_id',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Present', 'Present')], max_length=20)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='faithlink.event')),
                ('parishioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faithlink.parishioner')),
            ],
            options={
                'unique_together': {('parishioner', 'date', 'event')},
            },
        ),
        migrations.CreateModel(
            name='SacramentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sacrament', models.CharField(max_length=100)),
                ('date_received', models.DateField(default=django.utils.timezone.now)),
                ('place_received', models.CharField(max_length=255)),
                ('officiant', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('parishioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faithlink.parishioner')),
            ],
        ),
        migrations.DeleteModel(
            name='FaceEmbedding',
        ),
    ]
