# Generated by Django 5.1 on 2025-05-29 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faithlink', '0017_parishioner_parishioner_id_attendance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sacramentrecord',
            name='sacramentsss',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
