# Generated by Django 5.1 on 2025-06-02 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faithlink', '0018_sacramentrecord_sacramentsss'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sacramentrecord',
            name='sacramentsss',
        ),
    ]
