# Generated by Django 5.1 on 2025-06-03 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faithlink', '0019_remove_sacramentrecord_sacramentsss'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='mass_type',
            field=models.CharField(blank=True, choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Evening', 'Evening')], max_length=20, null=True),
        ),
    ]
