# Generated by Django 5.1 on 2025-06-09 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faithlink', '0021_event_description_event_image_event_is_announcement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
        migrations.RemoveField(
            model_name='event',
            name='is_announcement',
        ),
    ]
