# Generated by Django 5.1 on 2025-06-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faithlink', '0022_remove_event_description_remove_event_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/'),
        ),
    ]
