# Generated by Django 5.1 on 2025-07-06 13:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faithlink', '0024_alter_prayerrequest_parishioner'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donation',
            name='pickup_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
