# Generated by Django 5.1 on 2025-07-08 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faithlink', '0027_alter_donation_donor'),
    ]

    operations = [
        migrations.AddField(
            model_name='parishioner',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
