# Generated by Django 5.1 on 2025-07-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faithlink', '0028_parishioner_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donation',
            name='item_condition',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='donation',
            name='item_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='donation',
            name='payment_method',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='donation_items/'),
        ),
        migrations.AddField(
            model_name='donation',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='type',
            field=models.CharField(choices=[('money', 'Money'), ('item', 'Item')], default='money', max_length=10),
        ),
    ]
