# Generated by Django 5.2.5 on 2025-08-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faithlink', '0029_donation_approved_donation_item_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sacramentrecord',
            name='certificate_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sacramentrecord',
            name='certificate_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('None', 'None')], default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='sacramentrecord',
            name='requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
