# Generated by Django 5.2.5 on 2025-08-21 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faithlink', '0030_sacramentrecord_certificate_requested_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sacramentrecord',
            name='certificate_requested',
        ),
        migrations.RemoveField(
            model_name='sacramentrecord',
            name='certificate_status',
        ),
        migrations.RemoveField(
            model_name='sacramentrecord',
            name='requested_at',
        ),
    ]
