# Generated by Django 5.2.5 on 2025-08-21 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faithlink', '0031_remove_sacramentrecord_certificate_requested_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sacramentrecord',
            name='certificate_requested',
            field=models.BooleanField(default=False),
        ),
    ]
