# Generated by Django 5.2.5 on 2025-09-16 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faithlink', '0034_alter_donation_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='donation',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
