# Generated by Django 5.2.5 on 2025-09-29 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faithlink', '0036_alter_donation_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('gcash', 'GCash'), ('bank_transfer', 'Bank Transfer'), ('paypal', 'PayPal')], max_length=50, null=True),
        ),
    ]
