# Generated by Django 5.2.5 on 2025-09-29 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faithlink', '0037_alter_donation_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='status',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='transaction_id',
        ),
        migrations.AlterField(
            model_name='donation',
            name='payment_method',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
