# Generated by Django 5.2.5 on 2025-09-29 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faithlink', '0038_remove_donation_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='donation',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('gcash', 'GCash'), ('bank_transfer', 'Bank Transfer'), ('paypal', 'PayPal')], max_length=50, null=True),
        ),
    ]
