# Generated by Django 5.2.5 on 2025-09-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faithlink', '0039_donation_status_donation_transaction_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='payment_method',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
