# Generated by Django 5.2.5 on 2025-10-01 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faithlink', '0040_alter_donation_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sacrament', models.CharField(choices=[('Baptism', 'Baptism'), ('Confirmation', 'Confirmation'), ('Eucharist', 'Eucharist'), ('Marriage', 'Marriage'), ('Anointing of the Sick', 'Anointing of the Sick')], max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('linked_record', models.ForeignKey(blank=True, help_text='Optional: link this request to an actual record later', null=True, on_delete=django.db.models.deletion.SET_NULL, to='faithlink.sacramentrecord')),
                ('parishioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faithlink.parishioner')),
            ],
        ),
    ]
