# Generated by Django 5.2.5 on 2025-10-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faithlink', '0041_certificaterequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='sacramentrecord',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
