# Generated by Django 5.2.5 on 2025-10-13 14:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faithlink', '0042_sacramentrecord_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='prayerrequest',
            name='answered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prayerrequest',
            name='date_requested',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
