# Generated by Django 5.1 on 2025-04-02 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_parishioner',
            field=models.BooleanField(default=False),
        ),
    ]
